-- Self-Execution Mode (SEM) Tables
-- Tracks orchestrator interventions when doers fail

-- SEM interventions table
CREATE TABLE IF NOT EXISTS sem_interventions (
  intervention_id VARCHAR(255) PRIMARY KEY,
  run_id UUID NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  phase VARCHAR(50) NOT NULL,
  task_id VARCHAR(255),
  trigger VARCHAR(50) NOT NULL,
  original_doer VARCHAR(255) NOT NULL,
  context_snapshot JSONB NOT NULL,
  claimed_at TIMESTAMP NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMP,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  result JSONB,
  gate_score NUMERIC(5,2),
  cost_usd NUMERIC(10,4),
  tokens_used INTEGER,
  tools_used TEXT[],
  handback_status VARCHAR(50),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sem_interventions_run_id ON sem_interventions(run_id);
CREATE INDEX IF NOT EXISTS idx_sem_interventions_phase ON sem_interventions(phase);
CREATE INDEX IF NOT EXISTS idx_sem_interventions_status ON sem_interventions(status);
CREATE INDEX IF NOT EXISTS idx_sem_interventions_trigger ON sem_interventions(trigger);
CREATE INDEX IF NOT EXISTS idx_sem_interventions_claimed_at ON sem_interventions(claimed_at);

-- SEM execution log table
CREATE TABLE IF NOT EXISTS sem_execution_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  intervention_id VARCHAR(255) NOT NULL REFERENCES sem_interventions(intervention_id) ON DELETE CASCADE,
  timestamp TIMESTAMP NOT NULL DEFAULT NOW(),
  log_level VARCHAR(20) NOT NULL,
  message TEXT NOT NULL,
  metadata JSONB
);

CREATE INDEX IF NOT EXISTS idx_sem_execution_logs_intervention_id ON sem_execution_logs(intervention_id);
CREATE INDEX IF NOT EXISTS idx_sem_execution_logs_timestamp ON sem_execution_logs(timestamp);

-- SEM micro-plans table
CREATE TABLE IF NOT EXISTS sem_micro_plans (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  intervention_id VARCHAR(255) NOT NULL REFERENCES sem_interventions(intervention_id) ON DELETE CASCADE,
  goal TEXT NOT NULL,
  tasks JSONB NOT NULL,
  tests JSONB NOT NULL,
  estimated_tokens INTEGER,
  estimated_minutes INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sem_micro_plans_intervention_id ON sem_micro_plans(intervention_id);

-- Comments
COMMENT ON TABLE sem_interventions IS 'Tracks Self-Execution Mode interventions when orchestrator steps in for failed doers';
COMMENT ON COLUMN sem_interventions.trigger IS 'Why SEM was triggered: heartbeat_timeout, progress_stalled, schema_failure, tool_failure, gate_deadlock, doer_underperformance';
COMMENT ON COLUMN sem_interventions.handback_status IS 'Result of intervention: returned_to_doer, continued_to_next_phase, failed';
COMMENT ON TABLE sem_execution_logs IS 'Detailed execution logs for SEM interventions';
COMMENT ON TABLE sem_micro_plans IS 'Micro-plans generated by SEM for each intervention';
