global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ideamine'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - 'alerts/*.yml'

# Scrape configurations
scrape_configs:
  # Orchestrator metrics
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:9000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Worker metrics
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # API metrics
  - job_name: 'api'
    static_configs:
      - targets: ['api:9002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL metrics (using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics (using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
