apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ideamine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
      component: web
  template:
    metadata:
      labels:
        app: api
        component: web
    spec:
      containers:
        - name: api
          image: ideamine/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9002
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: PORT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: LOG_LEVEL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ideamine-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: ideamine-secrets
                  key: REDIS_URL
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ideamine-secrets
                  key: ANTHROPIC_API_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ideamine-secrets
                  key: JWT_SECRET
            - name: CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: CORS_ORIGINS
            - name: RATE_LIMIT_WINDOW_MS
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: RATE_LIMIT_WINDOW_MS
            - name: RATE_LIMIT_MAX_REQUESTS
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: RATE_LIMIT_MAX_REQUESTS
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 9002
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: ideamine
  labels:
    app: api
    component: web
spec:
  selector:
    app: api
    component: web
  ports:
    - port: 9002
      targetPort: 9002
      name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: ideamine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
