apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  namespace: ideamine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orchestrator
      component: core
  template:
    metadata:
      labels:
        app: orchestrator
        component: core
    spec:
      containers:
        - name: orchestrator
          image: ideamine/orchestrator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: NODE_ENV
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: LOG_LEVEL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ideamine-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: ideamine-secrets
                  key: REDIS_URL
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ideamine-secrets
                  key: ANTHROPIC_API_KEY
            - name: JAEGER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: ideamine-secrets
                  key: JAEGER_ENDPOINT
            - name: OTEL_SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: ideamine-secrets
                  key: OTEL_SERVICE_NAME
            - name: DEFAULT_TOKEN_BUDGET
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: DEFAULT_TOKEN_BUDGET
            - name: HEARTBEAT_INTERVAL_MS
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: HEARTBEAT_INTERVAL_MS
            - name: STALL_THRESHOLD_HEARTBEATS
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: STALL_THRESHOLD_HEARTBEATS
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: ideamine
spec:
  selector:
    app: orchestrator
    component: core
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
