# Secrets Configuration Template
#
# IMPORTANT: This is a template file. Do not commit actual secrets to version control!
# Create actual secrets using: kubectl create secret generic ideamine-secrets --from-env-file=.env
#
# Example:
# kubectl create secret generic ideamine-secrets \
#   --from-literal=database-url='postgresql://user:pass@postgres:5432/ideamine' \
#   --from-literal=redis-url='redis://redis:6379' \
#   --from-literal=anthropic-api-key='sk-ant-...' \
#   --from-literal=jwt-secret='your-random-secret' \
#   -n ideamine

apiVersion: v1
kind: Secret
metadata:
  name: ideamine-secrets
  namespace: ideamine
type: Opaque
stringData:
  # Database
  DATABASE_URL: "postgresql://ideamine:CHANGEME@postgres:5432/ideamine"

  # Redis
  REDIS_URL: "redis://redis:6379"

  # Anthropic API
  ANTHROPIC_API_KEY: "sk-ant-CHANGEME"

  # JWT Secret (for API authentication)
  JWT_SECRET: "CHANGEME-generate-random-secret"

  # Jaeger
  JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
  OTEL_SERVICE_NAME: "ideamine-orchestrator"
