apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: ideamine
spec:
  replicas: 10  # Start with 10 workers, scale with HPA
  selector:
    matchLabels:
      app: worker
      component: executor
  template:
    metadata:
      labels:
        app: worker
        component: executor
    spec:
      containers:
        - name: worker
          image: ideamine/worker:latest
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: NODE_ENV
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: LOG_LEVEL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ideamine-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: ideamine-secrets
                  key: REDIS_URL
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ideamine-secrets
                  key: ANTHROPIC_API_KEY
            - name: JAEGER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: ideamine-secrets
                  key: JAEGER_ENDPOINT
            - name: WORKER_CONCURRENCY
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: WORKER_CONCURRENCY
            - name: HEARTBEAT_INTERVAL_MS
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: HEARTBEAT_INTERVAL_MS
            - name: MAX_RETRIES
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: MAX_RETRIES
            - name: CHECKPOINT_INTERVAL_MS
              valueFrom:
                configMapKeyRef:
                  name: ideamine-config
                  key: CHECKPOINT_INTERVAL_MS
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "pgrep -f worker || exit 1"
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "pgrep -f worker || exit 1"
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa
  namespace: ideamine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: 5
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes
      policies:
        - type: Percent
          value: 50  # Scale down max 50% of pods at a time
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0  # Scale up immediately
      policies:
        - type: Percent
          value: 100  # Double pods at a time
          periodSeconds: 15
        - type: Pods
          value: 10  # Or add 10 pods at a time
          periodSeconds: 15
      selectPolicy: Max
